//! Card sprite atlas — each unique card appearance is rasterised ONCE
//! into an `Arc<Vec<u8>>` of straight-alpha RGBA8 pixels at exactly the
//! physical pixel size it'll be blitted to.
//!
//! At runtime, `paint_pile` blits those bytes via
//! `DrawCtx::draw_image_rgba_arc`. The wgpu backend keys its GPU texture
//! cache by `Arc::as_ptr`, so cloning an Arc across many cards shares
//! one GPU texture — every face-down card on the board reuses the same
//! card-back texture, every Ace of Spades shares one texture, etc.
//!
//! The atlas is rebuilt by `GameWidget` whenever the effective render
//! scale (playfield_scale × device DPR) changes. Rendering at exactly
//! the destination physical-pixel count means the blit is a 1:1 NEAREST
//! sample — pixels generated by AGG's antialiased rasteriser show up
//! on screen unfiltered, preserving every halftone the rasteriser
//! produced (no double-AA blur, no nearest-neighbour blockiness).

use std::collections::HashMap;
use std::sync::Arc;

use agg_gui::framebuffer::unpremultiply_rgba_inplace;
use agg_gui::text::Font;
use agg_gui::{Framebuffer, GfxCtx};

use crate::cards::{Card, Rank, Suit};
use crate::consts::{CARD_H, CARD_W};

use super::card_back::paint_card_back;
use super::card_face::paint_card_face;

#[derive(Clone, Copy, Hash, PartialEq, Eq)]
struct FaceKey {
    suit: Suit,
    rank: Rank,
}

pub struct CardSpriteAtlas {
    /// Sprite pixel size (atlas-internal) — equals the physical pixel
    /// area the card will occupy on screen.
    pub px_w: u32,
    pub px_h: u32,
    /// Effective render scale this atlas was built at
    /// (`playfield_scale × device_scale`). Used by `GameWidget` to
    /// detect when a rebuild is required.
    pub render_scale: f64,
    faces: HashMap<FaceKey, Arc<Vec<u8>>>,
    back: Arc<Vec<u8>>,
}

impl CardSpriteAtlas {
    /// Pre-rasterise all 52 card faces + 1 card back at exactly
    /// `CARD_W * scale × CARD_H * scale` physical pixels. Logical-to-
    /// physical scaling happens via `GfxCtx::scale(scale, scale)` so
    /// `paint_card_face` keeps drawing in logical card space.
    pub fn build(font: &Arc<Font>, scale: f64) -> Self {
        let scale = scale.max(0.5);
        let px_w = (CARD_W * scale).round().max(1.0) as u32;
        let px_h = (CARD_H * scale).round().max(1.0) as u32;

        let back = rasterise(px_w, px_h, scale, |ctx| {
            paint_card_back(ctx, 0.0, 0.0, CARD_W, CARD_H);
        });

        let mut faces = HashMap::with_capacity(52);
        for suit in Suit::ALL {
            for rank in Rank::ALL {
                let card = Card {
                    suit,
                    rank,
                    face_up: true,
                    deck_id: 0,
                };
                let pixels = rasterise(px_w, px_h, scale, |ctx| {
                    paint_card_face(ctx, &card, 0.0, 0.0, CARD_W, CARD_H, font);
                });
                faces.insert(FaceKey { suit, rank }, pixels);
            }
        }

        Self {
            px_w,
            px_h,
            render_scale: scale,
            faces,
            back,
        }
    }

    pub fn face(&self, suit: Suit, rank: Rank) -> Arc<Vec<u8>> {
        self.faces
            .get(&FaceKey { suit, rank })
            .expect("every face cached at build()")
            .clone()
    }

    pub fn back(&self) -> Arc<Vec<u8>> {
        self.back.clone()
    }
}

/// Rasterise `paint_fn` into a fresh `Framebuffer` of `(px_w, px_h)`
/// physical pixels. `paint_fn` draws in logical card space —
/// `(0, 0)..(CARD_W, CARD_H)` — and we pre-scale the GfxCtx by `scale`
/// so the AGG rasteriser produces exactly `(px_w × px_h)` pixels.
///
/// Framebuffer rows are Y-up bottom-up, but `draw_image_rgba_arc`
/// expects top-down RGBA — so we flip rows on the way out and convert
/// from premultiplied to straight alpha.
fn rasterise(
    px_w: u32,
    px_h: u32,
    scale: f64,
    paint_fn: impl FnOnce(&mut GfxCtx<'_>),
) -> Arc<Vec<u8>> {
    let mut fb = Framebuffer::new(px_w, px_h);
    {
        let mut ctx = GfxCtx::new(&mut fb);
        ctx.scale(scale, scale);
        paint_fn(&mut ctx);
    }
    let mut pixels = fb.pixels_flipped();
    unpremultiply_rgba_inplace(&mut pixels);
    Arc::new(pixels)
}
